require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'

target 'MittHelsingborg' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'MittHelsingborgTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  post_install do |installer|
    flipper_post_install(installer)

    installer.pods_project.targets.each do |t|
      # Fix for xCode build errors: https://github.com/facebook/react-native/issues/29709
      if t.name == "React-Core.common-AccessibilityResources"
        t.remove_from_project
      else
        t.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
        end
      end
    end
  end
end

target 'MittHelsingborg-tvOS' do
  # Pods for MittHelsingborg-tvOS

  target 'MittHelsingborg-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
