# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do

  desc "build the app with correct distribution signing"
  lane :build do
    
    # fetch the latest certificates and provisioning profile
    # todo: use match to automatically sync certs and profiles
    get_certificates(generate_apple_certs: false)
    get_provisioning_profile

    # increment build number
    build_number = latest_testflight_build_number + 1
    increment_build_number(build_number: build_number)

    # set xcode project to use the correct certificate and profile
    update_code_signing_settings(
      use_automatic_signing: false,
      code_sign_identity: "iPhone Distribution",
      profile_name: lane_context[SharedValues::SIGH_NAME]
    )
    
    # build app
    build_app(
      silent: true,
      suppress_xcode_output: true,
      include_symbols: true,
      include_bitcode: true
    )
  end


  desc "Push a new beta build to TestFlight"
  lane :beta do

    # run the build lane
    build

    # upload
    upload_to_testflight(
      skip_submission: true,
      notify_external_testers: false,

      # note: skipping this sacrifices some flexibility in post-processing but reduces CI minutes and costs significantly
      skip_waiting_for_build_processing: true
    )

  end

end
