# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    # Shall always be run! setup_circle_ci will:
    # Create a new temporary keychain.
    # Switch match to readonly mode to make sure CI does not create new code signing certificates or provisioning profiles.
    # Set up log and test result paths to be easily collectible.
    setup_circle_ci
  end
  
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "mitt_helsingborg_playground.xcodeproj")
    build_app(scheme: "mitt_helsingborg_playground")

    # upload_to_testflight
  end
end
