name: Android - Build

on:
  workflow_dispatch:
    inputs:
      forcedVersion:
        description: Force Version Number String
      forcedBuildNumber:
        description: Force Build Number

# prevents multiple build workflows from running
# (in-progress and queued will be cancelled in favor of pending)
concurrency:
  group: build-android-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and upload to Google Play
    environment: production
    runs-on: ubuntu-20.04

    steps:
      # checkout the repo
      # fetch-depth: 0 is required to fetch all tags to generate changelog
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      ######################
      # set .env file
      # content has to be encoded as base64 in order to preserve newlines
      # use "cat .env | base64 | pbcopy" to get pasteable content for GitHub secrets
      ######################

      - name: Set env vars
        env:
          DOTENV_CONTENTS_BASE64: ${{ secrets.DOTENV_CONTENTS_BASE64 }}
        run: |
          echo $DOTENV_CONTENTS_BASE64 | base64 -d > .env

      ######################
      # END set .env file
      ######################

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: cache yarn
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ secrets.CACHE_KEY_PREFIX }}-${{ hashFiles('**/yarn.lock') }}

      - name: update hash
        run: ./scripts/add-commit-hash-to-env.sh

      - name: yarn install
        run: yarn install

      - name: add credentials
        env:
          JSON_KEY_FILE_CONTENTS: ${{ secrets.ANDROID_JSON_KEY_FILE_CONTENTS }}
          ANDROID_KEYSTORE_PROPERTIES_BASE64: ${{ secrets.ANDROID_KEYSTORE_PROPERTIES_BASE64 }}
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          echo $JSON_KEY_FILE_CONTENTS > android/google-play-api-key.json
          echo $ANDROID_KEYSTORE_PROPERTIES_BASE64 | base64 -d > android/keystore.properties
          echo $ANDROID_KEYSTORE_BASE64 | base64 -d > android/app/mitt-helsingborg-upload-key.keystore

      - name: Setup Sentry
        env:
          SENTRY_PROPERTIES: ${{ secrets.SENTRY_PROPERTIES_BASE64 }}
        run: |
          ./scripts/setup-sentry-properties.sh

      - name: Build
        timeout-minutes: 60
        env:
          CONNECT_API_KEY_CONTENT: ${{ secrets.CONNECT_API_KEY_CONTENT }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FORCED_VERSION_NUMBER_STRING: ${{ github.event.inputs.forcedVersion }}
          FORCED_BUILD_NUMBER: ${{ github.event.inputs.forcedBuildNumber }}
          GIT_HEAD_REF: ${{ github.head_ref }}
          JSON_KEY_FILE: "./google-play-api-key.json"
          FASTLANE_SKIP_UPDATE_CHECK: 1
        run: |
          cd android
          fastlane android build --verbose
