name: Android - Build

on:
  workflow_dispatch:
    inputs:
      forcedVersion:
        description: Force Version Number String
      forcedBuildNumber:
        description: Force Build Number
      forcedEnvironment:
        description: Force environment used for .env file content

# prevents multiple build workflows from running
# (in-progress and queued will be cancelled in favor of pending)
concurrency:
  group: build-android-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and upload to Google Play
    environment: production
    runs-on: ubuntu-20.04

    steps:
      - name: stub
        run: echo "stub android build workflow"
