# Workflow for printing the changelog (debugging)

name: (debug) Print changelog

on:
  workflow_dispatch:

jobs:
  print_changelog:
    name: (debug) Print changelog
    environment: production
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1

      - name: Print changelog
        run: |
          cd ios
          fastlane print_changelog
